# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobufs/songs.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15protobufs/songs.proto\x12\x05songs\"S\n\x15RecommendationRequest\x12%\n\x08\x63\x61tegory\x18\x01 \x01(\x0e\x32\x13.songs.SongCategory\x12\x13\n\x0bmax_results\x18\x02 \x01(\x05\"L\n\x16RecommendationResponse\x12\x32\n\x0frecommendations\x18\x01 \x03(\x0b\x32\x19.songs.SongRecommendation\".\n\x12SongRecommendation\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t*H\n\x0cSongCategory\x12\x07\n\x03POP\x10\x00\x12\x0b\n\x07HIP_HOP\x10\x01\x12\x0e\n\nELECTRONIC\x10\x02\x12\x08\n\x04\x46OLK\x10\x04\x12\x08\n\x04ROCK\x10\x05\x32]\n\x0fRecommendations\x12J\n\tRecommend\x12\x1c.songs.RecommendationRequest\x1a\x1d.songs.RecommendationResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobufs.songs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SONGCATEGORY']._serialized_start=243
  _globals['_SONGCATEGORY']._serialized_end=315
  _globals['_RECOMMENDATIONREQUEST']._serialized_start=32
  _globals['_RECOMMENDATIONREQUEST']._serialized_end=115
  _globals['_RECOMMENDATIONRESPONSE']._serialized_start=117
  _globals['_RECOMMENDATIONRESPONSE']._serialized_end=193
  _globals['_SONGRECOMMENDATION']._serialized_start=195
  _globals['_SONGRECOMMENDATION']._serialized_end=241
  _globals['_RECOMMENDATIONS']._serialized_start=317
  _globals['_RECOMMENDATIONS']._serialized_end=410
# @@protoc_insertion_point(module_scope)
